# Default values for coffee-and-tea.

replicaCount: 2

image:
  repository: midzaru2011/coffee-and-tea-app
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

database:
  url: "jdbc:postgresql:/temp//CoffeeAndTea"
  username: "sasha"
  password: "password" # Это значение будет закодировано в Secret автоматически

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: false
  name: "Sasha"

env:
  SPRING_DATASOURCE_URL: "{{ .Values.database.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.database.username }}"