# Default values for coffee-and-tea.

replicaCount: 2

image:
  repository: midzaru2011/coffee-and-tea-app
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

database:
  url: jdbc:postgresql://158.160.34.71:5432/CoffeeAndTea
  username: "sasha"
  password: "password" # Это значение будет закодировано в Secret автоматически

env:
  SPRING_DATASOURCE_URL: "{{ .Values.database.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.database.username }}"