# Default values for coffee-and-tea.

replicaCount: 2

image:
  repository: midzaru2011/coffee-and-tea-app
  tag: "2.1.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8082
  targetPort: 8082

database:
  url: jdbc:postgresql://158.160.34.71:5432/CoffeeAndTea
  username: "sasha"
  password: "password" # Это значение будет закодировано в Secret автоматически

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  name: "Sasha"

env:
  SPRING_DATASOURCE_URL: "{{ .Values.database.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.database.username }}"