apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-and-tea.fullname" . }}-config
data:
  SPRING_DATASOURCE_URL: {{ .Values.database.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}