apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coffee-and-tea.fullname" . }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "coffee-and-tea.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "coffee-and-tea.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "coffee-and-tea.fullname" . }}-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "coffee-and-tea.fullname" . }}-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "coffee-and-tea.fullname" . }}-db-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: {{ .Values.service.targetPort }}
