apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffee-and-tea.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "coffee-and-tea.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
