name: Publish Helm Chart

on:
  push:
    branches:
      - main # Запускать только при пуше в ветку main
    paths:
      - "coffee-and-tea/**" # Ограничение на изменения в директории с Chart

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout кода репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Извлечение appVersion из сообщения коммита
    - name: Extract appVersion from commit message
      id: extract_app_version
      run: |
        # Получаем последнее сообщение коммита
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)

        # Используем регулярное выражение для извлечения appVersion
        APP_VERSION=$(echo "$COMMIT_MESSAGE" | grep -oP 'appVersion:\s*"\K[^"]+')

        # Если appVersion найден, сохраняем его как переменную окружения
        if [ -n "$APP_VERSION" ]; then
          echo "Extracted appVersion: $APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        else
          echo "No appVersion found in commit message. Skipping update."
          exit 0
        fi

    # 3. Обновление appVersion в Chart.yaml
    - name: Update Chart.yaml with new appVersion
      if: env.APP_VERSION != ''
      run: |
        # Обновляем поле appVersion в Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: \"${{ env.APP_VERSION }}\"/" ./coffee-and-tea/Chart.yaml

        # Проверяем, что файл был успешно обновлен
        cat ./coffee-and-tea/Chart.yaml  

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # 2. Установка Helm CLI
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    # 3. Упаковка Helm Chart
    - name: Package Helm Chart
      run: helm package ./coffee-and-tea

    # 4. Обновление индекса репозитория
    - name: Update Helm Index
      run: |
        helm repo index --url https://midzaru2011.github.io/helm-charts/ .

    # 5. Загрузка файлов в GitHub Pages
    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update of Helm Chart and index.yaml" || echo "No changes to commit"
        git push git@github.com:Midzaru2011/helm-charts.git main
